<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="CSCO-W-PF2S3T6E" failures="2" tests="3" name="Test" time="0.05" errors="0" timestamp="2021-12-07T09:30:07 IST">
  <testcase classname="com.tdd.TestCalc" name="TestOp1Greater" time="0.008"/>
  <testcase classname="com.tdd.TestCalc" name="TestOp1Less" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [Op1 less than 0] but found [9]">
      <![CDATA[java.lang.AssertionError: expected [Op1 less than 0] but found [9]
at com.tdd.TestCalc.TestOp1Less(TestCalc.java:27)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- TestOp1Less -->
  <testcase classname="com.tdd.TestCalc" name="TestOp2Greater" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [Op2 greater than 100] but found [101]">
      <![CDATA[java.lang.AssertionError: expected [Op2 greater than 100] but found [101]
at com.tdd.TestCalc.TestOp2Greater(TestCalc.java:21)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- TestOp2Greater -->
</testsuite> <!-- Test -->
